name: swift-testing-cross-compile-demo ci
on:
  push:
    branches:
      - '*'
  workflow_dispatch:
  pull_request:
    branches:
      - '*'

jobs:
  test-android:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: "Test Swift Package on Android"
        uses: skiptools/swift-android-action@main
        with:
          swift-version: '6.1'

  test-local:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: "Test Swift Package Locally"
        run: swift test

